export const portfolio = {
  name: 'Nurul Hasan',
  portrait: {
    src: '/nurul-hasan.jpg',
    alt: 'Portrait of Nurul Hasan',
  },
  role: 'Backend Developer | Java & Spring Boot',
  intro: 'B.Tech CSE (AI & ML) student building backend applications with Java and Spring Boot.',
  summary: 'I’m a B.Tech CSE (AI & ML) student with hands-on experience developing backend applications using Java and Spring Boot. My work has included REST APIs, security, persistence, and microservices technologies. I’m currently developing a microservices-based chatting application, and have completed backend projects through a CodeAlpha internship and a hackathon.',
  social: {
    github: 'https://github.com/nurulhasan321',
    linkedin: 'https://linkedin.com/in/nurulhasan82',
  },
  contact: {
    email: 'nurulhasan120120@gmail.com',
    phone: '+91 8250983815',
    location: 'Barasat, West Bengal, India',
  },
  skillGroups: [
    { title: 'Programming Languages', items: ['Java', 'Python', 'SQL'] },
    { title: 'Backend Development', items: ['Spring Boot', 'Spring Web', 'Spring WebFlux', 'FastAPI', 'REST APIs'] },
    { title: 'Java & Persistence', items: ['Spring Security', 'Hibernate', 'JPA', 'Spring Data JPA', 'Maven'] },
    { title: 'Microservices & Distributed Systems', items: ['Microservices Architecture', 'API Gateway', 'Eureka Service Discovery', 'Apache Kafka', 'Event-Driven Architecture'] },
    { title: 'Databases', items: ['PostgreSQL', 'MySQL'] },
    { title: 'Security', items: ['JWT', 'Authentication', 'Authorization', 'HttpOnly Cookies'] },
    { title: 'DevOps & Tools', items: ['Docker', 'Linux', 'Git', 'GitHub', 'IntelliJ IDEA', 'Postman'] },
    { title: 'AI/ML', items: ['Machine Learning', 'Natural Language Processing (NLP)', 'RAG Fundamentals'] },
  ],
  experience: {
    company: 'CodeAlpha',
    role: 'Backend Development Intern',
    status: 'Completed Internship',
    points: [
      'Engineered backend application components using Java, Spring Boot, and REST API standards.',
      'Implemented secure authentication and authorization using Spring Security and JWT.',
      'Configured JPA/Hibernate persistence for MySQL and PostgreSQL.',
      'Managed builds with Maven, containerized application components with Docker, and maintained version control with Git and GitHub.',
    ],
  },
  projects: [
    {
      title: 'Microservices Architecture Chatting Application',
      label: 'Featured · In Progress',
      featured: true,
      repositoryUrl: null,
      technologies: ['Java', 'Spring Boot', 'Spring Security', 'Kafka', 'Eureka Server', 'API Gateway', 'Hibernate', 'JPA', 'PostgreSQL', 'REST APIs', 'Spring WebFlux'],
      points: [
        'Developing independent Spring Boot backend services with REST APIs for a microservices-based chat application.',
        'Uses an API Gateway, Eureka service discovery, and Kafka for asynchronous, event-driven communication.',
        'Authentication and User services use PostgreSQL with Hibernate/JPA; JWT with HttpOnly cookies, Spring WebFlux exploration, and planned Redis caching are part of the project.',
      ],
    },
    {
      title: 'Savory Restaurant Management System',
      label: 'CodeAlpha project',
      repositoryUrl: null,
      technologies: ['Java', 'Spring Boot', 'MySQL', 'Spring Security', 'JPA', 'JWT', 'REST APIs', 'Docker'],
      points: [
        'Developed a backend-driven management system using Java, Spring Boot, and REST APIs.',
        'Implemented Spring Security with JWT for authentication and role-based authorization.',
        'Designed MySQL schemas with JPA/Hibernate and containerized the service with Docker.',
      ],
    },
    {
      title: 'URL Shortener',
      label: 'CodeAlpha project',
      repositoryUrl: null,
      technologies: ['Java', 'Spring Boot', 'PostgreSQL', 'Spring Data JPA', 'Spring Security', 'REST APIs', 'Docker', 'Maven'],
      points: [
        'Built a Spring Boot backend with REST APIs for short-code generation, URL validation, and redirection.',
        'Integrated PostgreSQL using Spring Data JPA for persistent link data management and validation logic.',
        'Configured Spring Security and packaged application artifacts with Docker and Maven.',
      ],
    },
    {
      title: 'Fraud/Phishing Email Detector',
      label: 'Hackathon project',
      repositoryUrl: null,
      technologies: ['Python', 'Machine Learning', 'NLP'],
      points: [
        'Developed an AI/ML email classification system to detect fraudulent and phishing content during a hackathon.',
        'Applied NLP for text preprocessing, feature extraction, and training machine learning classification models.',
      ],
    },
  ],
  education: {
    institution: 'Brainware University',
    location: 'Barasat, West Bengal',
    degree: 'B.Tech in Computer Science & Engineering (Artificial Intelligence & Machine Learning)',
    dates: '2024 – 2028',
    status: 'Currently in progress',
  },
  languages: [
    { name: 'Bengali', level: 'Fluent' },
    { name: 'Hindi', level: 'Fluent' },
    { name: 'English', level: 'Working Proficiency' },
  ],
  sections: [
    { label: 'About', href: '#about' },
    { label: 'Skills', href: '#skills' },
    { label: 'Experience', href: '#experience' },
    { label: 'Projects', href: '#projects' },
    { label: 'Education', href: '#education' },
    { label: 'Contact', href: '#contact' },
  ],
  footerYear: '2026',
  seo: {
    title: 'Nurul Hasan | Backend Developer',
    description: 'Nurul Hasan — B.Tech CSE (AI & ML) student focused on Java and Spring Boot backend development.',
  },
  copy: {
    heroAvailability: 'B.Tech CSE (AI & ML) · 2024—2028',
    viewProjects: 'View Projects',
    downloadCv: 'Download CV',
    contact: 'Contact',
    focusEyebrow: '01 / CURRENT FOCUS',
    focusTitle: 'Building backend systems',
    focusDescription: 'Java · Spring Boot · Microservices',
    exploreWork: 'Explore selected work',
    scrollExplore: 'SCROLL TO EXPLORE',
    aboutEyebrow: 'A LITTLE ABOUT ME',
    aboutTitle: 'Backend development\nin focus.',
    aboutAside: 'Learning through building — from backend internship work to a microservices chat application.',
    skillsEyebrow: 'TOOLKIT',
    skillsTitle: 'Skills & technologies',
    skillsNote: 'A toolkit spanning backend development, data, and AI/ML.',
    experienceEyebrow: 'EXPERIENCE',
    experienceTitle: 'Experience',
    projectsEyebrow: 'SELECTED WORK',
    projectsTitle: 'Projects',
    projectsNote: 'Backend projects from internship work, a hackathon, and current development.',
    repoNote: 'Project repository URLs were not included in the CV.',
    repoLabel: 'Link unavailable',
    educationEyebrow: 'EDUCATION',
    educationTitle: 'Education',
    languagesEyebrow: 'LANGUAGES',
    languagesTitle: 'Languages',
    contactEyebrow: 'GET IN TOUCH',
    contactTitle: 'Let’s build something\nthoughtful.',
    emailMe: 'Email me',
    backToTop: 'BACK TO TOP',
    emailLabel: 'Email',
    phoneLabel: 'Phone',
    locationLabel: 'Location',
    github: 'GitHub',
    linkedin: 'LinkedIn',
    homeLabel: 'Nurul Hasan, home',
    mainNavigation: 'Main navigation',
    menuOpen: 'Open navigation menu',
    menuClose: 'Close navigation menu',
    currentFocus: 'Current focus',
    lightMode: 'Switch to light mode',
    darkMode: 'Switch to dark mode',
  },
}
